@startuml Диаграмма состояний приложения

state "Об игре" as Об_игре
state "Настройка имени" as Имя

[*] --> Меню : запуск приложения
Меню --> Меню : выбор пункта для фокусировки
Меню --> Игра : выбор "Играть"
Меню --> Рекорды : выбор "Рекорды"
Меню --> Об_игре : выбор "Об игре"
Меню --> Имя : переход на пункт\n"Ваше имя"
Меню --> [*] : выход

Игра --> Меню : возврат

Об_игре --> Об_игре : прокрутка страниц
Об_игре --> Меню : возврат

Рекорды --> Меню : возврат

Имя --> Имя : изменение имени,\nлюбые клавиши
Имя --> Меню : подтверждение,\nнажатие Enter
Имя --> Меню : отмена,\nнажатие Escape

@enduml