@startuml Диаграмма последовательности для процесса игры
actor Игрок as player
participant "Приложение" as application
participant "Игра Agario" as game

player -> application: Запуск приложения
activate application
player <- application: Отображение меню
|||
player -> application: Выбор пункта "Играть"
application -> game: Запуск игры
activate game
player <- game: Отображение экрана игры
|||
==Игровая сессия (начало)==
player -> game: Перемещение, поглощение еды и\nдругих клеток, набор массы
game -> game: Генерация еды
game -> game: Перемещение врагов
==Смерть (может не произойти)==
player -> game: Потеря всей массы
==Возрождение (если была Смерть)==
player <- game: Возрождение на случайном месте
==Пауза (может не произойти)==
player -> game: Установка паузы
game <- game: Переход в приостановленное состояние
player -> game: Снятие паузы
game <- game: Восстановление активного состояния
==Возобновление (если была Пауза)==
==Игровая сессия (конец)==
player -> game: Выход из игры
==Завершение игры==
application <- game: Завершение игры
deactivate game
application <- application: Сохранение в глобальную таблицу\nлидеров по необходимости
player <- application : Отображение меню
@enduml