@startuml Agario MVC Example
hide circle
hide members

class Model
class View
class Controller

Model <- Controller
View <- Controller
View -> Model
@enduml

@startuml Agario MVC Linked
hide circle
hide members

entity AgarioModel
entity AgarioMenu
entity ControllerGame
entity ViewGame
entity ControllerMenu
entity ViewMenu

AgarioModel <.. ControllerGame
AgarioModel <.. ViewGame

ViewGame <.. ControllerGame

ControllerGame <|-- ControllerGameWPF
ControllerGame <|-- ControllerGameConsole

ViewGame <|-- ViewGameWPF
ViewGame <|-- ViewGameConsole

AgarioMenu <.. ControllerMenu
AgarioMenu <.. ViewMenu

ViewMenu <.. ControllerMenu

ViewMenu <|-- ViewMenuWPF
ViewMenu <|-- ViewMenuConsole

ControllerMenu <|-- ControllerMenuWPF
ControllerMenu <|-- ControllerMenuConsole

ControllerGame <-- ControllerMenu
@enduml
